server:
  port: 8081
spring:
  application:
    name: skyBackend
  datasource:
    url: jdbc:mysql://localhost:3306/{填写数据库地址}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #redis
  data:
    redis:
      host: localhost
      port: 6379
  #qwenAI
  ai:
    dashscope:
      api-key: {填写api-key}
      embedding:
        options:
          model: text-embedding-v4
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema-mysql.sql
#Mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  file:
    name: log/sky.log
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.springframework.ai.chat.client.advisor: debug
#minio
minio:
  endpoint: {填写存储桶地址}
  accessKey: {填写accessKey}
  secretKey: {填写secretKey}
  bucket: {填写存储桶名称}
