
server:
  port: 8091

spring:
  application:
    name: mcp-server
#  main:
#    web-application-type: none
#    banner-mode: off
  # 默认 dev 环境
#  profiles:
#    active: dev
  ai:
    dashscope:
      api-key: sk-ee20842afe994bf8a12a26370e9afaae
      chat:
        options:
          model: qwen-turbo-latest

    mcp:
      client:
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json
      server:
        stdio: true # 启用stdio模式
        name: mcp-server
        version: 0.0.1
  mandatory-file-encoding: UTF-8
endpoint:
  mianshiya:
    searchQuestion: http://localhost:8081/posts/all
    resultLink: visitor/%s

